### ISSUE TITLE
Add simple survey questions relating to the P4B scenario data

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/scenarioSelector#5]
P4B scenario data is publicly available and can be found here: 
https://www.transitionmonitor.com/pacta-for-banks-2020/methodology-and-supporting-materials/

We can write sample survey questions that filter these scenarios. Some of the questions might filter the scenarios on data that exists already in the scenario themselves (eg. "What sectors do you want to cover", "What regions", "Production or Emission Factors"). 

Other questions will rely on meta-data that we will need to extract from the supporting document.

**Comment by jdhoffa** [comment]
Proposed questions with criteria that exists already in the datasets:

I show here a pseudo-reprex. If you point it to a folder containing all the scenario data found in the link above, it will format them and output a scenario meta-data list (including a specification indicating if the scenario is a "production" scenario, or "emission_factor" scenario). 

We can use this "meta-data" to start with, and generate a series of survey questions that filter the meta data. 

Other questions will involve data that isn't computable from the .csv themselves (information that can be found in the "supporting" materials or in the publications). I will think of survey questions of this variety secondarily. 

``` r
library(readr)
library(dplyr)
library(purrr)


# Compute Meta-Data -------------------------------------------------------
filter_production <- function(x) {
  any(grepl("tmsr", names(x)))
}

filter_emission_factor <- function(x) {
  any(grepl("emission_factor", names(x)))
}

files <- list.files(path = "~/Downloads/", pattern = ".csv", full.names = TRUE)

scenarios <- purrr::map(files, read_csv)

production_scenario_meta <- scenarios[sapply(scenarios, filter_production) == TRUE] %>% 
  bind_rows() %>% 
  select(scenario_source, scenario, sector, region) %>% 
  distinct() %>% 
  mutate(scenario_type = "production")

emission_factor_scenario_meta <- scenarios[sapply(scenarios, filter_emission_factor) == TRUE] %>% 
  bind_rows()%>% 
  select(scenario_source, scenario, sector, region) %>% 
  distinct() %>% 
  mutate(scenario_type = "emission_factor")

scenario_meta_data <- rbind(production_scenario_meta, emission_factor_scenario_meta)


# Questions ---------------------------------------------------------------
# Question 1: Do you wish to set production targets or emission factor targets?
answers <- c(
  "production", 
  "emission_factor",
  "both"
) 

filtered scenarios <- {
  if (answers == "both") {
    scenario_meta_data
  } else{
    filter(scenario_meta_data, scenario_type == "answers")
  }
}

# Question 2: Which sectors are you interested in studying? 
answers <- c(
  "coal",
  "oil and gas",
  "oil & gas", # it is unfortunate that this is duplicated with two different 
  "power",
  "automotive",
  "cement",
  "steel",
  "aviation"
)

filtered_scenarios <- filter(scenario_meta_data, sector %in% answers)

# Question 3: Are you interested in studying a particular region?
answers <- c(TRUE, FALSE)

# Question 3.1: Which regions? 
answers <- unique(scenario_meta_data$region)

filtered_scenarios <- filter(scenario_meta_data, region %in% answers) 
```

**Comment by jdhoffa** [comment]
Proposed questions that rely on external meta-data:

What I mean by this, is that you will see that the result of these questions will involve me setting two variables: 
`two_degree_scenarios` and `net_zero_scenarios`.
To know which scenarios fall into either category, you would need to read an external publication (or the supporting material 2DII provides). 

``` r 
# Question 4: Do you wish to set a 2-degree aligned target?
answers <- c(TRUE, FALSE)

#define meta-data
two_degree_scenarios <- c("isf_nz", "nze2021", "b2ds", "sds", "2ds")

filtered_scenarios <- filtered scenarios <- {
  if (answers) {
    filter(scenario_meta_data, scenario %in% two_degree_scenarios)
  } else{
    scenario_meta_data
  }
}

# Question 5: Do you wish to set a net-zero emissions target?
answers <- c(TRUE, FALSE)

#define meta-data
net_zero_scenarios <- c("isf_nz", "nze2021")

filtered_scenarios <- filtered scenarios <- {
  if (answers) {
    filter(scenario_meta_data, scenario %in% net_zero_scenarios)
  } else{
    scenario_meta_data
  }
}
```

**Comment by maurolepore** [comment]
Here I'll collect some thoughts as I implement the questions.

* Because all scenarios are now into a single dataset, the implementation looks different to what's shown above.

* Whenever we allow multiple selections, we are faced with the challenge of how to plot them all. One solution is to facet over such variables but this doesn't scale up well, as the number of panels grows rapidly, and only two variables are most clearly displayed along the two-dimensions (`x ~ y`) of the page (we can fit more with e.g. `x + y ~ z` but this is hard to read). Instead I prefer to force the user to pick a specific value of every variable that is common to both "production" and "emission factor" scenarios. This means, for example, that I would force users to pick one single value of `sector` but allow multiple values of `technology`.

``` r
library(dplyr, warn.conflicts = FALSE)
devtools::load_all()
#> ℹ Loading scenarioSelector

# `sector` applies to both "production" and "emission factor" scenarios
# I would force users to pick a single value of `sector`
scenarios %>% filter(is_production(variable)) %>% distinct(sector)
#> # A tibble: 5 x 1
#>   sector     
#>   <chr>      
#> 1 automotive 
#> 2 power      
#> 3 coal       
#> 4 oil and gas
#> 5 oil & gas
scenarios %>% filter(is_emission_factor(variable)) %>% distinct(sector)
#> # A tibble: 3 x 1
#>   sector  
#>   <chr>   
#> 1 cement  
#> 2 steel   
#> 3 aviation

# `technology` applies to "production" but not "emission factor" scenarios
# I would allow multiple values of `technology` and use a facet
scenarios %>% filter(is_production(variable)) %>% distinct(technology)
#> # A tibble: 13 x 1
#>    technology   
#>    <chr>        
#>  1 electric     
#>  2 hybrid       
#>  3 ice          
#>  4 coalcap      
#>  5 gascap       
#>  6 hydrocap     
#>  7 nuclearcap   
#>  8 oilcap       
#>  9 renewablescap
#> 10 coal         
#> 11 gas          
#> 12 oil          
#> 13 fuelcell
scenarios %>% filter(is_emission_factor(variable)) %>% distinct(technology)
#> # A tibble: 1 x 1
#>   technology
#>   <chr>     
#> 1 <NA>
```

<sup>Created on 2021-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
All "questions" are now implemented. See https://twodii.shinyapps.io/scenarioSelector/
